### ISSUE TITLE
can't download mp3 with 192kbps and 328kbps

### ISSUE THREAD

**Issue by dr-ishigami-senku** [Simatwa/y2mate-api#1]
ERROR:root:Zero media hunted with params : {quality : 328kbps, format : mp3  } #192kbps and 328kbps
ERROR:root:Empty `third_dict` parameter parsed : {}

the code:
from y2mate_api import Handler

api = Handler("https://youtu.be/jNQXAC9IVRw?si=oBZoGXNBZ9AeWOPO")
for audio_metadata in api.run(format="mp3", quality="328kbps"):
	api.save(third_dict=audio_metadata)

**Comment by Simatwa** [comment]
This is an issue with the host *(y2mate.com)*, on rare occasions  you will find mp3s that support those qualities. Mostly 128kbps, which is the standard bitrate. Hope they will consider other bitrates with time. At the moment let's settle for 128kbps.
