### ISSUE TITLE
I think its broken

### ISSUE THREAD

**Issue by TiagoMarante** [Simatwa/y2mate-api#2]
I was just trying this today and i got this.

![image](https://github.com/user-attachments/assets/4a2a3dcc-c3e4-4791-91c5-5c4ed2a47465)

**Comment by John4650-hub** [comment]
Also getting the same issue while using github actions

**Comment by Simatwa** [comment]
Working on it

**Comment by davidjeddy** [comment]
Similar issue in v1.2.2

<img width="847" alt="image" src="https://github.com/user-attachments/assets/1ddedfb6-4698-4f53-933a-6bd0c6492553" />
