### ISSUE TITLE
185.240.17.207root:~# y2mate -f mp3 jvvla 02:03:41 - INFO : y2mate launched - v1.2.2 02:03:41 - ERROR : Failed to load history - Extra data: line 28360 column 2 (char 2439260) 02:03:42 - ERROR : Cannot download file of content-length 0 bytes root@Blue:~#

### ISSUE THREAD

**Issue by Kajsjdnwnp22** [Simatwa/y2mate-api#3]
185.240.17.207root@Blue:~# y2mate -f mp3 jvla
02:03:41 - INFO : y2mate launched - v1.2.2
02:03:41 - ERROR : Failed to load history - Extra data: line 28360 column 2 (char 2439260)
02:03:42 - ERROR : Cannot download file of content-length 0 bytes
root@Blue:~#

**Comment by Simatwa** [comment]
To fix `Failed to load history` run `$ y2mate --clear`.

The download failure is caused by ant-bot mechanism. Using US proxies will help in that.
